### ISSUE TITLE
Error: Invalid JSON received from the Clover API

### ISSUE THREAD

**Issue by Wingjam** [deepalimittalgit/clover_ecomm_app#1]
Hi,

First, thanks for your sample app!

I just cloned your repo, add the .env file with the right information and roll it all up.
When testing "Pay with iFrame SDK" with a test card, I got "Invalid JSON received from the Clover API" error. Did I do something wrong?

![image](https://user-images.githubusercontent.com/7340240/81606258-bb05ee80-93a0-11ea-8c95-04727175e202.png)

Full error output : 
```bash
[0] Getting error in Charge API -  { Error: Invalid JSON received from the Clover API
[0]     at IncomingMessage.res.once (path/to/repo/clover_ecomm_app-master/node_modules/clover-ecomm-sdk/lib/net/Resources.js:150:15)
[0]     at Object.onceWrapper (events.js:286:20)
[0]     at IncomingMessage.emit (events.js:203:15)
[0]     at endReadableNT (_stream_readable.js:1145:12)
[0]     at process._tickCallback (internal/process/next_tick.js:63:19)
[0]   raw:
[0]    { message: 'Invalid JSON received from the Clover API',
[0]      response: { message: [Object], error: [Object] },
[0]      exception:
[0]       ReferenceError: GenericError is not defined
[0]           at Function.generate (path/to/repo/clover_ecomm_app-master/node_modules/clover-ecomm-sdk/lib/Error.js:57:9)
[0]           at IncomingMessage.res.once (path/to/repo/clover_ecomm_app-master/node_modules/clover-ecomm-sdk/lib/net/Resources.js:143:39)
[0]           at Object.onceWrapper (events.js:286:20)
[0]           at IncomingMessage.emit (events.js:203:15)
[0]           at endReadableNT (_stream_readable.js:1145:12)
[0]           at process._tickCallback (internal/process/next_tick.js:63:19),
[0]      requestId: undefined },
[0]   rawType: undefined,
[0]   code: undefined,
[0]   param: undefined,
[0]   detail: undefined,
[0]   headers: undefined,
[0]   requestId: undefined,
[0]   statusCode: undefined }
```

**Comment by dkwan8888** [comment]
If API responses are correct, JSON should be able to parse them correctly.
Use your .env in 
https://docs.clover.com/clover-platform/reference/charges

To test and see whats the response.

**Comment by deepalimittalgit** [comment]
Hi Wing,
Thanks for reaching out. I tried with my sample sandbox credentials and I am able to charge successfully. 
You can share your charge request to me DM- deepali.mittal@clover.com , I will try if anything wrong with request. You would need to provide API Token in Charge Request, which should have beeen part of your .env file. 
<img width="556" alt="Screen Shot 2020-05-13 at 12 45 06 PM" src="https://user-images.githubusercontent.com/52582198/81857885-bc0d5c00-9517-11ea-990f-7aa7ef5927fe.png">

<img width="699" alt="Screen Shot 2020-05-13 at 12 44 58 PM" src="https://user-images.githubusercontent.com/52582198/81857919-c92a4b00-9517-11ea-8cf8-4260314c276c.png">
